version: '3.8'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:

  teamcity-sqlserver-docker:
    container_name: teamcity-sqlserver-docker
    image: sqlserver/teamcity
    restart: always
    profiles: ["docker"]
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SQLSERVER_PWD}
      SA_PASSWORD: ${SQLSERVER_PWD}
      MSSQL_PID: Evaluation
    ports:
      - 1433:1433

  teamcity-sqlserver-ubuntu:
    container_name: teamcity-sqlserver-ubuntu
    image: sqlserver/teamcity
    restart: always
    profiles: ["ubuntu"]
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SQLSERVER_PWD}
      MSSQL_PID: Evaluation
    ports:
      - 1434:1433

  teamcity-sqlserver-nodes:
    container_name: teamcity-sqlserver-nodes
    image: sqlserver/teamcity
    restart: always
    profiles: ["nodes"]
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SQLSERVER_PWD}
      MSSQL_PID: Evaluation
    ports:
      - 1433:1433

  teamcity-db-ubuntu:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    profiles: ["ubuntu"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./teamcity/ubuntu/db:/var/lib/postgresql/data
    ports:
      - 5434:5432

  teamcity-db-nodes:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    profiles: ["nodes"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./teamcity/nodes/db:/var/lib/postgresql/data
    ports:
      - 5435:5432

  nginx:
    image: nginx:1.19
    profiles: ["nodes"]
    ports:
      - 8222:8222
    volumes:
      - ./nginx:/etc/nginx/conf.d

  teamcity-server-docker:
    image: jetbrains/teamcity-server
    profiles: ["docker"]
    ports:
      - ${TEAMCITY_PORT}:8111
    volumes:
      - ./data/teamcity/docker:/data/teamcity_server/datadir
      - ./teamcity/docker/logs/teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - teamcity-sqlserver-docker

  teamcity-server-ubuntu:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION_UBUNTU}
    profiles: ["ubuntu"]
    ports:
      - ${TEAMCITY_PORT}:8111
    volumes:
      - ./data/teamcity/ubuntu:/data/teamcity_server/datadir
      - ./teamcity/ubuntu/logs/teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - teamcity-sqlserver-ubuntu

  teamcity-server-nodes:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    profiles: ["nodes"]
    volumes:
      - ./data/teamcity/nodes:/data/teamcity_server/datadir
      - ./teamcity/nodes/logs/teamcity-server-logs1:/opt/teamcity/logs
    ports:
      - ${TEAMCITY_PORT}:8111
    depends_on:
      - teamcity-sqlserver-nodes

  teamcity-agent-ubuntu-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION_UBUNTU}-linux-sudo
    profiles: ["ubuntu"]
    privileged: true
    volumes:
      - ./teamcity/ubuntu/agents/teamcity-agent-conf-1:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

  teamcity-agent-ubuntu-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION_UBUNTU}-linux-sudo
    profiles: ["ubuntu"]
    privileged: true
    volumes:
      - ./teamcity/ubuntu/agents/teamcity-agent-conf-2:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

  teamcity-agent-nodes-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
    profiles: ["nodes"]
    environment:
      SERVER_URL: http://nginx:8222
    volumes:
      - ./teamcity/nodes/agents/teamcity-agent-conf1:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock

  teamcity-agent-nodes-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
    profiles: ["nodes"]
    environment:
      SERVER_URL: http://nginx:8222
    volumes:
      - ./teamcity/nodes/agents/teamcity-agent-conf2:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock

  node1:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    profiles: ["nodes"]
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./teamcity/nodes/node1/data:/data/teamcity_server/node_datadir
      - ./teamcity/nodes/node1/logs/teamcity-server-logs2:/opt/teamcity/logs
    ports:
      - 8112:8111
    environment:
      TEAMCITY_SERVER_OPTS: -Dteamcity.server.nodeId=node1 -Dteamcity.server.rootURL=http://teamcity:8111 -Dteamcity.data.path=/data/teamcity_server/datadir -Dteamcity.node.data.path=/data/teamcity_server/node_datadir
    